=== Marioms03/Lenguaje-de-marcas/Ejercicios/restricciones.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="restricciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona">
                    <xs:complexType>
                        <xs:all><!-- el xs all me indica que puedo poner los elementos en el orden que yo quiera pero deben aparecer, el min puede ser 0 o 1, el max solamente 1-->
                            <xs:element name="nombre" type="xs:string" /> 
                            <xs:element name="apellidos" type="xs:string" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>  
                <xs:element name="empresa">
                    <xs:complexType>
                        <xs:choice><!-- con choice solamente podemos elegir una en xml, en este caso empleado o miembro-->
                            <xs:element name="empleado" type="xs:string" />
                            <xs:element name="miembro" type="xs:string" />
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="edad">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer"><!-- sirve para crear una restriccion entre dos valores, en este caso la edad en el xml debe estar entre 0 y 120 años-->
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="120"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element> 
                <xs:element name="coche">
                    <xs:simpleType>
                        <xs:restriction base="xs:string"><!-- sirve para crear una restriccion , en este caso solo puedes elegir entre Audi y Mercedes-->
                            <xs:enumeration value="Audi"/>
                            <xs:enumeration value="Mercedes"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element> 
                <!-- Esto es la definición del tipo "tipoSemana" -->
                <xs:element name="semana" type="tipoSemana">
                <xs:simpleType name="tipoSemana">
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Lunes"/>
                        <xs:enumeration value="Martes"/>
                        <xs:enumeration value="Miércoles"/>
                        <xs:enumeration value="Jueves"/>
                        <xs:enumeration value="Viernes"/>
                        <xs:enumeration value="Sábado"/>
                        <xs:enumeration value="Domingo"/>
                    </xs:restriction>
                </xs:simpleType>
                </xs:element>
                <xs:element name="letras"> <!-- 3 letras de la a-z o A-Z, los carácteres se cuentan por los corchetes cerrados-->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z][a-zA-Z][a-zA-Z]"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="telefono"> <!-- puedes elegir infinitos números entre el 0 y el 9 o ninguno-->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:pattern value="([0-9])*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
               <xs:element name="curso"> <!-- tengo que elegir como minimo una letra entre la a-z y entre la A-Z-->
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="([a-z][A-Z])+"/>
                      </xs:restriction>
                    </xs:simpleType>
                </xs:element> 
                <xs:element name="genero"><!-- puede elegir entre los dos-->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:pattern value="male|female"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="password"><!-- solo podemos elegir 8 caracteres entre la a-z, A-Z, 0-9-->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9]{8}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>  
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Marioms03/Lenguaje-de-marcas/Ejercicios/xml y xsd/restricciones.xml
<?xml version="1.0"?>

<restricciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="restricciones.xsd">
    <persona>
        <nombre></nombre>
        <apellidos></apellidos>
    </persona>
    <empresa>
        <empleado>Juan</empleado>
    </empresa>
    <edad>5</edad>
    <coche>Audi</coche>
    <semana>Lunes</semana>
    <letras>aBh</letras>
    <telefono>938347549</telefono>
    <curso>aA</curso>
    <genero>male</genero>
    <password>2736456A</password>
</restricciones>
