=== Marioms03/Lenguaje-de-marcas/Ejercicios/XML y DTD/futbol.dtd
<!ELEMENT futbol (equipos)>
<!ELEMENT equipos (nombre, copas, jugadores, equipacion, partidos, estadio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT copas (#PCDATA)>
<!ELEMENT jugadores (pichichi)>
<!ELEMENT pichichi (nombrejugador, fechanacimiento, goles, tarjetas)>
<!ELEMENT nombrejugador (#PCDATA)>
<!ELEMENT fechanacimiento (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
<!ELEMENT tarjetas (amarillas, rojas)>
<!ELEMENT amarillas (#PCDATA)>
<!ELEMENT rojas (#PCDATA)>
<!ELEMENT equipacion (primera, segunda)>
<!ELEMENT primera (#PCDATA)>
<!ELEMENT segunda (#PCDATA)>
<!ELEMENT partidos (jugados)>
<!ELEMENT jugados (ganados, perdidos, empatados)>
<!ELEMENT ganados (#PCDATA)>
<!ELEMENT perdidos (#PCDATA)>
<!ELEMENT empatados (#PCDATA)>
<!ELEMENT estadio (nombreestadio, capacidad)>
<!ELEMENT nombreestadio (#PCDATA)>
<!ELEMENT capacidad (#PCDATA)>

=== Marioms03/Lenguaje-de-marcas/Ejercicios/XML y DTD/futbol.xml
<?xml version="1.0"?>
<!DOCTYPE futbol SYSTEM "futbol.dtd">

<futbol>
    <vacio></vacio>
    <equipos>
        <nombre>Betis</nombre>
        <copas>0</copas>
        <jugadores>
            <pichichi>
                <nombrejugador>Joaquin</nombrejugador>
                <fechanacimiento>1980-10-10</fechanacimiento>
                <goles>100</goles>
                <tarjetas>
                    <amarillas>1</amarillas>
                    <rojas>0</rojas>
                </tarjetas>
            </pichichi>
        </jugadores>
        <equipacion>
            <primera>Blanca y verde</primera>
            <segunda>Azul y blanca</segunda>
        </equipacion>
        <partidos>
            <jugados>
                <ganados>100</ganados>
                <perdidos>10</perdidos>
                <empatados>0</empatados>
            </jugados>
        </partidos>
        <estadio>
            <nombreestadio>Benito Villamar√≠n</nombreestadio>
            <capacidad>60000</capacidad>
        </estadio>
    </equipos>
</futbol>
