=== Marioms03/Lenguaje-de-marcas/Ejercicios/XML y DTD/medicamento.dtd
<!ELEMENT FARMACIA (MEDICAMENTO+)>
<!ELEMENT MEDICAMENTO (NOMBRE, ADMINISTRACION, DOSIS)>
<!ELEMENT NOMBRE (GENERICO, (COMERCIAL)+)>
<!ELEMENT GENERICO (#PCDATA)>
<!ELEMENT COMERCIAL (#PCDATA)>
<!ELEMENT ADMINISTRACION (#PCDATA)>
<!ELEMENT DOSIS (#PCDATA)>


<!ATTLIST NOMBRE ID CDATA #REQUIRED>
<!ATTLIST ADMINISTRACION TIPO CDATA #REQUIRED>

=== Marioms03/Lenguaje-de-marcas/Ejercicios/XML y DTD/medicamento.xml
<?xml version="1.0"?>
<!DOCTYPE FARMACIA SYSTEM "medicamento.dtd">

<FARMACIA>
    <MEDICAMENTO>
        <NOMBRE ID="1">
            <GENERICO>DOLOR DE CABEZA</GENERICO>
            <COMERCIAL>PARACETAMOL</COMERCIAL>
        </NOMBRE>
        <ADMINISTRACION TIPO="INTRAMUSCULAR">8H/24H</ADMINISTRACION>
        <DOSIS>30 MG</DOSIS>
    </MEDICAMENTO>
    <MEDICAMENTO>
        <NOMBRE ID="2">
            <GENERICO>DOLOR DE ESTOMAGO</GENERICO>
            <COMERCIAL>UBIPROFENO</COMERCIAL>
        </NOMBRE>
        <ADMINISTRACION TIPO="ORAL">8H/24H</ADMINISTRACION>
        <DOSIS>20 MG</DOSIS>
    </MEDICAMENTO>
</FARMACIA>
