=== Marioms03/Lenguaje-de-marcas/Ejercicios/xml y xsd/calendario.xsd
<?xsd version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="calendario">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="trimestre">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="asignatura">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="6"/>
                                </xs:sequence>
                            </xs:complexType>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="tema" minOccurs="1" maxOccurs="10">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="nombre" type="xs:string"/>
                                                <xs:element name="notamedia">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="teoria" type="decimal" minOccurs="2" maxOccurs="10"/>
                                                            <xs:element name="practica" type="decimal" minOccurs="2" maxOccurs="10"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="numero" type="xs:integer"/>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="fechasexamenes" type="xs:date" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ciclo" type="xs:string"/>
    </xs:complexType>




</xs:element>
</xs:schema>

=== Marioms03/Lenguaje-de-marcas/Ejercicios/calendario.xml
<?xml version="1.0"?>

<calendario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="calendario.xsd">
    <trimestre numero="primero">
        <asignatura>
            <nombre>LLMM</nombre> <!-- min 1 max 6-->
            <tema numero="4"> <!-- min 1 max 10-->
                <nombre>RSS</nombre>
                <notamedia>
                    <teoria>8,4</teoria> <!-- min 2 max 10-->
                    <practica>7,7</practica> <!-- min 2 max 10-->
                </notamedia>
            </tema>
            <fechasexamenes>2021/03/07</fechasexamenes> <!-- numero indefinido (unbounded)-->
        </asignatura>
    </trimestre>
</calendario>
